version: "3.8"

services:
    app:
        image: php:8.2-apache
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "8000:80"
        depends_on:
            - db
        working_dir: /var/www/html
        restart: unless-stopped
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret
        command: >
            bash -c "
            apt-get update &&
            apt-get install -y libzip-dev unzip libpng-dev libonig-dev libxml2-dev curl &&
            docker-php-ext-install pdo_mysql zip && 
            a2enmod rewrite &&
            apache2-foreground
            "

    db:
        image: mysql:8.0
        container_name: mysql_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
